/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Issues an anonymous session cookie if none is present, and returns the current session id. Dev1 calls this once on app boot before any other request. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journey-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Drives Screen 2 (Journey Selection). */
        get: operations["listJourneyPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journey-packs/{journey_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the goal schema and display labels for one pack. Drives Screen 3 (Goal & Basic Info), which renders its form dynamically from goal_schema. */
        get: operations["getJourneyPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Drives Screen 10 (My Journeys). Scoped to the caller's session. */
        get: operations["listJourneys"];
        put?: never;
        /** @description Creates a journey and its v1 snapshot. Called by Screen 3 on Continue. */
        post: operations["createJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Drives Screen 4 (Current Status) and rehydration on resume. */
        get: operations["getJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Drives Screen 5. Recomputed on every call from the current snapshot. */
        get: operations["getRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Stores and interprets evidence and returns a DETERMINISTIC consequence preview. Creates NO snapshot. Drives Screen 6 -> Screen 7. */
        post: operations["uploadEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description THE ONLY MUTATION ENDPOINT. Runs Deterministic Check, then atomically creates a snapshot, an audit event and a diff. Drives Screen 7 Continue -> Screen 8. */
        post: operations["applyAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolves one AMBIGUOUS field. Updates ONLY the targeted field, snapshots, recomputes. */
        post: operations["submitClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journeys/{journey_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Wipes journey data and re-seeds packs, scenarios and the demo session. */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JourneyType: "LENDING" | "INSURANCE" | "CREDIT_CARD" | "KYC" | "ACCOUNT_OPENING" | "INVESTMENT";
        /**
         * @description Deterministic enum. There is no readiness score anywhere in this API.
         * @enum {string}
         */
        Readiness: "READY" | "NOT_READY" | "NEEDS_REVIEW" | "DEAD_END";
        /** @enum {string} */
        JourneyStatus: "IN_PROGRESS" | "COMPLETED" | "NEEDS_REVIEW";
        /** @enum {string} */
        FieldStatus: "SATISFIED" | "BLOCKED" | "AMBIGUOUS";
        /** @enum {string} */
        ErrorCode: "INVALID_JOURNEY_TYPE" | "VALIDATION_ERROR" | "ACTION_INVALID" | "ACTION_STALE" | "NEEDS_REVIEW" | "DEAD_END" | "AI_TIMEOUT" | "AI_MALFORMED_OUTPUT" | "EVIDENCE_CONFLICT";
        ErrorEnvelope: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Human-readable and safe to render directly to the user. */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                /**
                 * Format: uuid
                 * @description Present on ACTION_STALE so the client can resync without a second call.
                 */
                current_snapshot_id?: string;
            };
        };
        JourneyPackSummary: {
            journey_type: components["schemas"]["JourneyType"];
            /** @example Loan / Lending */
            display_name: string;
            /** @example Complete your loan application */
            description: string;
            /**
             * @description Dev1 maps these six tokens to icon components.
             * @enum {string}
             */
            icon: "rupee" | "shield" | "card" | "id" | "bank" | "chart";
            flagship_demo: boolean;
            /** @enum {string} */
            lifecycle_status: "DRAFT" | "VALIDATED" | "SUPPORTED";
        };
        GoalFieldSpec: {
            key: string;
            /** @enum {string} */
            type: "enum" | "money" | "number" | "text" | "date" | "boolean";
            label: string;
            required: boolean;
            placeholder?: string;
            help_text?: string;
            min?: number;
            max?: number;
            options?: {
                value: unknown;
                label: string;
            }[];
        };
        JourneyPackDetail: components["schemas"]["JourneyPackSummary"] & {
            schema_version: string;
            goal_schema: components["schemas"]["GoalFieldSpec"][];
            supports_natural_language: boolean;
            /** @description Journey-specific copy. Known keys: goal_heading, status_heading, status_subtext, evidence_heading, ready_heading, ready_subtext, recommendation_heading. Dev1 falls back to a default if a key is absent. */
            ui_labels: {
                [key: string]: string;
            };
        };
        FieldState: {
            key: string;
            /** @example Income verification */
            label: string;
            status: components["schemas"]["FieldStatus"];
            value?: unknown;
            /** @description Pre-formatted for display */
            display_value?: string;
            /** @description Why this is blocked. Rendered on the blocker card. */
            explanation?: string;
            /** @description The action that resolves this field. Powers the "Resolve ->" button. */
            resolve_action_id?: string;
            mandatory?: boolean;
            ambiguity?: {
                ambiguity_id?: string;
                reason?: string;
                question?: string;
                /** @enum {string} */
                answer_type?: "CHOICE" | "MONEY" | "NUMBER" | "TEXT" | "DATE" | "BOOLEAN";
                choices?: {
                    value?: unknown;
                    label?: string;
                }[];
            } | null;
        };
        /** @description Journey progress only. NOT readiness, approval, eligibility or a score. Dev1 renders this as "3/7 Completed". Never render it as a percentage or gauge. */
        ProgressCounts: {
            completed: number;
            pending: number;
            blockers: number;
            total: number;
        };
        JourneyStateResponse: {
            /** Format: uuid */
            journey_id: string;
            journey_type: components["schemas"]["JourneyType"];
            schema_version: string;
            /** Format: uuid */
            snapshot_id: string;
            version_number: number;
            readiness: components["schemas"]["Readiness"];
            status: components["schemas"]["JourneyStatus"];
            /** @description Ordered for display. Only fields with display=true and not NOT_APPLICABLE. */
            fields: components["schemas"]["FieldState"][];
            progress: components["schemas"]["ProgressCounts"];
            /** @description Present when readiness is NEEDS_REVIEW. Exactly one at a time. */
            pending_clarification?: components["schemas"]["FieldState"] | null;
            display: {
                /** @example Personal Loan */
                title: string;
                /** @example ₹5,00,000 · Home Renovation */
                summary: string;
            };
            /** Format: date-time */
            updated_at?: string;
        };
        ActionOption: {
            action_id: string;
            title: string;
            /**
             * @description Tells Dev1 which UI to open. EVIDENCE -> Screen 6. FORM -> generic action modal rendered from input_schema. CLARIFICATION -> NeedsReviewCard.
             * @enum {string}
             */
            kind: "EVIDENCE" | "FORM" | "CLARIFICATION";
            why?: string;
            unlocks: string[];
            /** @description Allowed doc_type values for EVIDENCE actions. */
            accepts?: string[];
            /** @description Field specs for FORM actions. Same renderer as the goal form. */
            input_schema?: components["schemas"]["GoalFieldSpec"][];
        };
        RecommendationResponse: {
            /** Format: uuid */
            snapshot_id: string;
            readiness: components["schemas"]["Readiness"];
            /** @description Null when readiness is READY or DEAD_END. */
            recommendation: components["schemas"]["ActionOption"] | null;
            /** @description Deterministically valid actions only. Safe to render as selectable. */
            alternatives: components["schemas"]["ActionOption"][];
            minimum_path_length: number;
            /**
             * @description Diagnostic. Dev1 may show it in a dev-only badge, never in demo UI.
             * @enum {string}
             */
            source?: "AI_RANKED" | "PLANNER_FALLBACK";
        };
        /** @description Output of deterministic simulation. Screen 7's "Expected Outcome" renders THIS, never AI text. */
        SimulationPreview: {
            newly_satisfied: {
                key?: string;
                label?: string;
            }[];
            newly_unlocked: {
                action_id?: string;
                title?: string;
            }[];
            still_blocked?: {
                key?: string;
                label?: string;
            }[];
            predicted_readiness: components["schemas"]["Readiness"];
            progress_before: components["schemas"]["ProgressCounts"];
            progress_after: components["schemas"]["ProgressCounts"];
        };
        JourneyDiff: {
            from_version: number;
            to_version: number;
            fields_changed: {
                key: string;
                label: string;
                from_status: components["schemas"]["FieldStatus"];
                to_status: components["schemas"]["FieldStatus"];
                display_value?: string;
                /** @example ACTION:UPLOAD_INCOME_PROOF */
                cause?: string;
                /** @description true if changed by cascade */
                cascaded?: boolean;
            }[];
            actions_unlocked: string[];
            actions_removed: string[];
            readiness: {
                from?: components["schemas"]["Readiness"];
                to?: components["schemas"]["Readiness"];
            };
            progress: {
                from?: components["schemas"]["ProgressCounts"];
                to?: components["schemas"]["ProgressCounts"];
            };
        };
        EvidenceResponse: {
            /** Format: uuid */
            evidence_id: string;
            filename: string;
            /** Format: date-time */
            uploaded_at: string;
            size_bytes?: number;
            interpretation: {
                /** @description confidence >= the pack mapping's threshold AND no conflicts. */
                verified: boolean;
                confidence: number;
                detected: {
                    key?: string;
                    label?: string;
                    /** @example ₹85,000 */
                    display_value?: string;
                }[];
                /** @description AI-written, plain text, never rendered as HTML. */
                summary: string;
                conflicts: {
                    ambiguity_id?: string;
                    field?: string;
                    message?: string;
                }[];
            };
            proposed_action_id?: string | null;
            consequence_preview?: components["schemas"]["SimulationPreview"] | null;
            diff_preview?: components["schemas"]["JourneyDiff"] | null;
            /** @description When true, Dev1 shows NeedsReviewCard instead of the Continue button. */
            requires_review: boolean;
        };
        ActionResponse: {
            journey: components["schemas"]["JourneyStateResponse"];
            diff: components["schemas"]["JourneyDiff"];
            /** @description Saves Dev1 a round trip after every action. */
            next_recommendation?: components["schemas"]["RecommendationResponse"] | null;
        };
        JourneyListItem: {
            /** Format: uuid */
            journey_id: string;
            journey_type: components["schemas"]["JourneyType"];
            display_name: string;
            icon: string;
            title: string;
            summary: string;
            status: components["schemas"]["JourneyStatus"];
            readiness: components["schemas"]["Readiness"];
            progress?: components["schemas"]["ProgressCounts"];
            /** Format: date-time */
            updated_at: string;
            /**
             * @description Where Dev1 should route on resume. Server decides, client obeys.
             * @enum {string}
             */
            resume_screen?: "STATUS" | "RECOMMENDATION" | "NEEDS_REVIEW" | "COMPLETE";
        };
    };
    responses: {
        /** @description Not found, or not owned by this session (deliberately indistinguishable) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description VALIDATION_ERROR or INVALID_JOURNEY_TYPE */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description ACTION_STALE. No mutation occurred. Client must refetch and recompute. */
        StaleAction: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description ACTION_INVALID. No mutation occurred. */
        InvalidAction: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        JourneyIdPath: string;
        JourneyTypePath: components["schemas"]["JourneyType"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        db: boolean;
                        packs_loaded: number;
                        packs_supported?: number;
                        /** @enum {string} */
                        ai_provider: "mock" | "llm";
                        git_sha?: string;
                    };
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    /** @description pf_session=<opaque>; HttpOnly; SameSite=Lax; Secure; Path=/ */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session_id: string;
                        /** @description true if newly issued this request */
                        created: boolean;
                    };
                };
            };
        };
    };
    listJourneyPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All journey packs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        packs: components["schemas"]["JourneyPackSummary"][];
                    };
                };
            };
        };
    };
    getJourneyPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_type: components["parameters"]["JourneyTypePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pack detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyPackDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listJourneys: {
        parameters: {
            query?: {
                status?: components["schemas"]["JourneyStatus"];
                journey_type?: components["schemas"]["JourneyType"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journeys for this session, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        journeys: components["schemas"]["JourneyListItem"][];
                    };
                };
            };
        };
    };
    createJourney: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    journey_type: components["schemas"]["JourneyType"];
                    /** @description Key/value map matching the pack's goal_schema. Keys and value types are validated server-side against that schema; unknown keys are rejected. */
                    goal: {
                        [key: string]: unknown;
                    };
                    /** @description Optional secondary input, parsed by AI into the same goal map. */
                    natural_language?: string;
                };
            };
        };
        responses: {
            /** @description Journey created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStateResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    getJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current journey state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStateResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One recommendation plus valid alternatives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF/JPEG/PNG, max 10 MB. Omit when using manual_fields.
                     */
                    file?: string;
                    /** @description JSON object, used by the "Enter Details" tab instead of a file. */
                    manual_fields?: string;
                    /** @example SALARY_SLIP */
                    doc_type: string;
                    /** Format: uuid */
                    expected_snapshot_id: string;
                };
            };
        };
        responses: {
            /** @description Interpretation plus preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["StaleAction"];
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    applyAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example UPLOAD_INCOME_PROOF */
                    action_id: string;
                    /** Format: uuid */
                    expected_snapshot_id: string;
                    /** Format: uuid */
                    idempotency_key: string;
                    /** @description Matches the action's input_schema; { evidence_id } for EVIDENCE actions. */
                    input?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Action applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            409: components["responses"]["StaleAction"];
            422: components["responses"]["InvalidAction"];
        };
    };
    submitClarification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example INCOME_MISMATCH */
                    ambiguity_id: string;
                    /** @example monthly_income */
                    field: string;
                    answer: unknown;
                    /** Format: uuid */
                    expected_snapshot_id: string;
                };
            };
        };
        responses: {
            /** @description Clarification applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            409: components["responses"]["StaleAction"];
            422: components["responses"]["InvalidAction"];
        };
    };
    getDiff: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                journey_id: components["parameters"]["JourneyIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diff between two snapshot versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyDiff"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resetDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reset?: boolean;
                        elapsed_ms?: number;
                    };
                };
            };
            /** @description Bad or missing demo secret */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
