from enum import StrEnum


class AuditEventType(StrEnum):
    """The 7 canonical audit event types for PaytmFlow."""

    JOURNEY_CREATED = "JOURNEY_CREATED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_REJECTED = "ACTION_REJECTED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"
    CLARIFICATION_ANSWERED = "CLARIFICATION_ANSWERED"
    STATE_TRANSITION = "STATE_TRANSITION"
