from enum import StrEnum


class JourneyType(StrEnum):
    LENDING = "LENDING"
    INSURANCE = "INSURANCE"
    CREDIT_CARD = "CREDIT_CARD"
    KYC = "KYC"
    ACCOUNT_OPENING = "ACCOUNT_OPENING"
    INVESTMENT = "INVESTMENT"


class Readiness(StrEnum):
    READY = "READY"
    NOT_READY = "NOT_READY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    DEAD_END = "DEAD_END"


class JourneyStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class FieldStatus(StrEnum):
    SATISFIED = "SATISFIED"
    BLOCKED = "BLOCKED"
    AMBIGUOUS = "AMBIGUOUS"


class ErrorCode(StrEnum):
    INVALID_JOURNEY_TYPE = "INVALID_JOURNEY_TYPE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    ACTION_INVALID = "ACTION_INVALID"
    ACTION_STALE = "ACTION_STALE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    DEAD_END = "DEAD_END"
    AI_TIMEOUT = "AI_TIMEOUT"
    AI_MALFORMED_OUTPUT = "AI_MALFORMED_OUTPUT"
    EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    REVIEW_CASE_STALE = "REVIEW_CASE_STALE"
    REVIEW_CASE_LOCKED = "REVIEW_CASE_LOCKED"
    REVIEW_CASE_INVALID_TRANSITION = "REVIEW_CASE_INVALID_TRANSITION"


class ReviewerRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    REVIEW_OFFICER = "REVIEW_OFFICER"


class ReviewCaseStatus(StrEnum):
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ADDITIONAL_INFO_REQUIRED = "ADDITIONAL_INFO_REQUIRED"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class ReviewCasePriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ReviewResolutionType(StrEnum):
    EVIDENCE_SUFFICIENT = "EVIDENCE_SUFFICIENT"
    REQUEST_ADDITIONAL_INFORMATION = "REQUEST_ADDITIONAL_INFORMATION"
    EVIDENCE_CANNOT_BE_VERIFIED = "EVIDENCE_CANNOT_BE_VERIFIED"
    CUSTOMER_INFO_NEEDS_CORRECTION = "CUSTOMER_INFO_NEEDS_CORRECTION"
    ESCALATE_FOR_SPECIALIST_REVIEW = "ESCALATE_FOR_SPECIALIST_REVIEW"


class PackIcon(StrEnum):
    RUPEE = "rupee"
    SHIELD = "shield"
    CARD = "card"
    ID = "id"
    BANK = "bank"
    CHART = "chart"


class LifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    SUPPORTED = "SUPPORTED"


class FieldType(StrEnum):
    ENUM = "enum"
    MONEY = "money"
    NUMBER = "number"
    TEXT = "text"
    DATE = "date"
    BOOLEAN = "boolean"


class ActionKind(StrEnum):
    EVIDENCE = "EVIDENCE"
    FORM = "FORM"
    CLARIFICATION = "CLARIFICATION"


class RecommendationSource(StrEnum):
    AI_RANKED = "AI_RANKED"
    PLANNER_FALLBACK = "PLANNER_FALLBACK"


class ResumeScreen(StrEnum):
    STATUS = "STATUS"
    RECOMMENDATION = "RECOMMENDATION"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COMPLETE = "COMPLETE"


class AnswerType(StrEnum):
    CHOICE = "CHOICE"
    MONEY = "MONEY"
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    DATE = "DATE"
    BOOLEAN = "BOOLEAN"
