/**
 * Judge-facing synthetic demo documents (frontend/public/demo-documents/),
 * generated by backend/app/docai/dataset/generate_demo_samples.py. Only the
 * doc_types the flagship LENDING journey actually requires evidence for -
 * never invented for journeys/doc_types with no real sample committed.
 */
export interface DemoDocument {
  docType: string;
  label: string;
  fileName: string;
  path: string;
}

const DEMO_DOCUMENTS: Record<string, DemoDocument> = {
  SALARY_SLIP: {
    docType: 'SALARY_SLIP',
    label: 'Sample Salary Slip',
    fileName: 'sample-salary-slip.pdf',
    path: '/demo-documents/sample-salary-slip.pdf',
  },
  OFFER_LETTER: {
    docType: 'OFFER_LETTER',
    label: 'Sample Offer Letter',
    fileName: 'sample-offer-letter.pdf',
    path: '/demo-documents/sample-offer-letter.pdf',
  },
};

/** Returns the first accepted doc_type (in order) that has a real demo document, if any. */
export function getDemoDocumentForAcceptedTypes(
  acceptedDocTypes: string[] | undefined
): DemoDocument | undefined {
  if (!acceptedDocTypes) return undefined;
  for (const docType of acceptedDocTypes) {
    const demo = DEMO_DOCUMENTS[docType];
    if (demo) return demo;
  }
  return undefined;
}
